### ISSUE TITLE
Clone / duplicate script?

### ISSUE THREAD

**Issue by Piega** [coinkiwi/kraken_api#1]
Not an https://github.com/beldur/kraken-go-api-client clone??

**Comment by coinkiwi** [comment]
Thanks for the note. This is not a clone, but should provide the same functionality (duplicate). Slightly different approach to some of the encoding schemes, more stress on type safety and automated internal and e2e tests. The kraken-go-api-client utilised more the map[string]string and interface{} in the serialisation/deserialization routines originally when I've looked at it back at the start of the project. Perhaps now they are both closer to each other than before.
